import { Star } from './types';

export const STARS: Star[] = [
  {
    id: 'proxima-centauri',
    name: 'Proxima Centauri',
    constellation: 'Centaurus',
    distanceLy: 4.24,
    spectralClass: 'M5.5Ve',
    rightAscension: '14h 29m',
    declination: '-62° 40′',
    apparentMag: 11.13,
  },
  {
    id: 'alpha-centauri-a',
    name: 'Alpha Centauri A',
    constellation: 'Centaurus',
    distanceLy: 4.37,
    spectralClass: 'G2V',
    rightAscension: '14h 39m',
    declination: '-60° 50′',
    apparentMag: -0.01,
  },
  {
    id: 'barnards-star',
    name: "Barnard's Star",
    constellation: 'Ophiuchus',
    distanceLy: 5.96,
    spectralClass: 'M4Ve',
    rightAscension: '17h 57m',
    declination: '+04° 41′',
    apparentMag: 9.54,
  },
  {
    id: 'wolf-359',
    name: 'Wolf 359',
    constellation: 'Leo',
    distanceLy: 7.78,
    spectralClass: 'M6Ve',
    rightAscension: '10h 56m',
    declination: '+07° 00′',
    apparentMag: 13.54,
  },
  {
    id: 'lalande-21185',
    name: 'Lalande 21185',
    constellation: 'Ursa Major',
    distanceLy: 8.29,
    spectralClass: 'M2V',
    rightAscension: '11h 03m',
    declination: '+35° 58′',
    apparentMag: 7.47,
  },
  {
    id: 'sirius-a',
    name: 'Sirius A',
    constellation: 'Canis Major',
    distanceLy: 8.58,
    spectralClass: 'A1V',
    rightAscension: '06h 45m',
    declination: '-16° 42′',
    apparentMag: -1.46,
  },
  {
    id: 'luyten-726-8',
    name: 'Luyten 726-8 A',
    constellation: 'Cetus',
    distanceLy: 8.73,
    spectralClass: 'M5.5Ve',
    rightAscension: '01h 39m',
    declination: '-17° 57′',
    apparentMag: 12.56,
  },
  {
    id: 'ross-154',
    name: 'Ross 154',
    constellation: 'Sagittarius',
    distanceLy: 9.68,
    spectralClass: 'M3.5Ve',
    rightAscension: '18h 49m',
    declination: '-23° 50′',
    apparentMag: 10.44,
  },
  {
    id: 'epsilon-eridani',
    name: 'Epsilon Eridani',
    constellation: 'Eridanus',
    distanceLy: 10.48,
    spectralClass: 'K2V',
    rightAscension: '03h 32m',
    declination: '-09° 27′',
    apparentMag: 3.73,
  },
  {
    id: 'tau-ceti',
    name: 'Tau Ceti',
    constellation: 'Cetus',
    distanceLy: 11.91,
    spectralClass: 'G8.5V',
    rightAscension: '01h 44m',
    declination: '-15° 56′',
    apparentMag: 3.50,
  },
];
